name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/**'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/**'
      - 'README.md'

jobs:
  BuildISO:
    name: Build ISO
    runs-on: ubuntu-latest
    steps:
    - name: Clone tree
      uses: actions/checkout@v2
      with:
        submodules: recursive
        path: nxdk_pgraph_tests
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          llvm \
          lld \
          libsdl2-dev \
          libsdl2-image-dev
        pip3 install nv2a-vsh
    - name: Compile
      run: |
        cd nxdk_pgraph_tests
        make -j $(grep -c processor /proc/cpuinfo) ENABLE_PROGRESS_LOG=y RUNTIME_CONFIG_PATH="e:/nxdk_pgraph_tests/pgraph_tests.cnf" DUMP_CONFIG_FILE=y
    - name: Create release
      if: github.ref == 'refs/heads/main'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "xiso containing pgraph tests"
        files: |
          nxdk_pgraph_tests/nxdk_pgraph_tests.iso
